apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: tool
stringData:
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
