apiVersion: batch/v1
kind: Job
metadata:
  name: tool-job
  namespace: tool
spec:
  template:
    metadata:
    spec:
      restartPolicy: Never
      containers:
        - image: ${DOCKER_USERNAME}/tool:latest
          name: tool-job
          env:
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_DEFAULT_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
